apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
    env: dev
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      name: load-generator
      labels:
        app: load-generator
        env: dev
        version: "0.1.0dev"
    spec:
      serviceAccountName: pubsub-loadgen
      securityContext:
        fsGroup: 1000
      containers:
        - name: load-generator
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp /home/loadgenerator/postgresql/* /home/loadgenerator/.postgresql &&
                    chmod 0600 /home/loadgenerator/.postgresql/postgresql.key
                    # the above is a workaround to get round the permissions as currently we cant mount it without doing this
          image: eu.gcr.io/census-rm-ci/rm/census-rm-load-generator:latest
          imagePullPolicy: Always
          tty: true
          stdin: true
          resources:
            requests:
              cpu: "3"
              memory: "10Gi"
            limits:
              cpu: "3"
              memory: "10Gi"
          volumeMounts:
            - name: cloud-sql-certs
              mountPath: "/home/loadgenerator/postgresql"
              readOnly: true
          env:
            - name: OFFLINE_RECEIPT_TOPIC_NAME
              value: "offline-receipt-topic"
            - name: OFFLINE_RECEIPT_TOPIC_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: offline-receipt-topic-project
            - name: RECEIPT_TOPIC_ID
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: receipt-topic-name
            - name: RECEIPT_TOPIC_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: receipt-topic-project-id
            - name: FULFILMENT_CONFIRMED_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: fulfilment-confirmed-topic-name
            - name: FULFILMENT_CONFIRMED_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: fulfilment-confirmed-project
            - name: QM_UNDELIVERED_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: qm-undelivered-project-id
            - name: EQ_FULFILMENT_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: eq-fulfilment-topic-name
            - name: EQ_FULFILMENT_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: eq-fulfilment-project-id
            - name: QM_UNDELIVERED_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: pubsub-config
                  key: qm-undelivered-topic-name
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-host
                  name: rabbitmq-host
            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-port
                  name: rabbitmq-host
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: RABBIT_USERNAME
                  name: rabbitmq-cred
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBIT_PASSWORD
                  name: rabbitmq-cred
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-credentials
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-credentials
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db-host
                  name: db-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: db-port
                  name: db-config
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db-name
                  name: db-config
      volumes:
        - name: cloud-sql-certs
          secret:
            defaultMode: 256
            items:
            - key: root.crt
              path: root.crt
            - key: postgresql.crt
              path: postgresql.crt
            - key: postgresql.key
              path: postgresql.key
            secretName: cloud-sql-certs
