apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: perf-test
  name: perf-test-consume-<QUEUE>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-test
  template:
    metadata:
      labels:
        app: perf-test
    spec:
      containers:
        - image: pivotalrabbitmq/perf-test
          imagePullPolicy: Always
          name: perf-test
          args:
            [
              "--uri",
              "amqp://<USERNAME>:<PASSWORD>@<HOST>",
              "--rate",
              "1",  # messages per second
              "--producers",
              "0",
              "--consumers",
              "1",
              "--exchange",
              "<EXCHANGE>",
              "--queue",
              "<QUEUE NAME>",
              "--predeclared"
            ]
#          # Resource limits/requests?
#          resources:
#            requests:
#              cpu: "1"
#              memory: "1Gi"
#            limits:
#              cpu: "1"
#              memory: "1Gi"
